//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuon()
        {
            this.PhieuPhats = new HashSet<PhieuPhat>();
            this.ViPhams = new HashSet<ViPham>();
        }
    
        public int MaPhieuMuon { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<System.DateTime> NgayNhanSach { get; set; }
        public Nullable<System.DateTime> HanTra { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public decimal PhiMuon { get; set; }
        public string TrangThai { get; set; }
        public string MaDocGia { get; set; }
        public Nullable<int> MaThuThu { get; set; }
        public int MaSach { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual ThuThu ThuThu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuPhat> PhieuPhats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViPham> ViPhams { get; set; }
    }
}
