//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQuanLyThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLThuVienEntities : DbContext
    {
        public QLThuVienEntities()
            : base("name=QLThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuPhat> PhieuPhats { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<ThuThu> ThuThus { get; set; }
        public virtual DbSet<ViPham> ViPhams { get; set; }
        public virtual DbSet<v_DanhSachSach> v_DanhSachSach { get; set; }
        public virtual DbSet<v_DocGia> v_DocGia { get; set; }
        public virtual DbSet<v_PhieuMuon> v_PhieuMuon { get; set; }
        public virtual DbSet<v_PhieuPhat> v_PhieuPhat { get; set; }
        public virtual DbSet<v_SachQuaHan> v_SachQuaHan { get; set; }
        public virtual DbSet<v_ThongBao> v_ThongBao { get; set; }
        public virtual DbSet<v_ViPham> v_ViPham { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_DangNhap_Result> sp_DangNhap(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhap_Result>("sp_DangNhap", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_GhiNhanViPhamQuaHanThanhToan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GhiNhanViPhamQuaHanThanhToan");
        }
    
        public virtual int sp_GuiThongBao(string maDocGia, string noiDung, ObjectParameter ketQua)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuiThongBao", maDocGiaParameter, noiDungParameter, ketQua);
        }
    
        public virtual int sp_GuiYeuCauMuon(string maDocGia, Nullable<int> maSach, ObjectParameter ketQua)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuiYeuCauMuon", maDocGiaParameter, maSachParameter, ketQua);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_HuyPhieuMuon(Nullable<int> maPhieuMuon, string maDocGia, ObjectParameter ketQua)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyPhieuMuon", maPhieuMuonParameter, maDocGiaParameter, ketQua);
        }
    
        public virtual int sp_KhoaTaiKhoanViPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhoaTaiKhoanViPham");
        }
    
        public virtual int sp_KiemTraQuaHanThanhToan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KiemTraQuaHanThanhToan");
        }
    
        public virtual int sp_KiemTraQuaHanTraSach(Nullable<int> maPhieuMuon, ObjectParameter ketQua)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KiemTraQuaHanTraSach", maPhieuMuonParameter, ketQua);
        }
    
        public virtual int sp_LapPhieuPhat(Nullable<int> maPhieuMuon, ObjectParameter ketQua)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LapPhieuPhat", maPhieuMuonParameter, ketQua);
        }
    
        public virtual ObjectResult<sp_LichSuMuonSach_Result> sp_LichSuMuonSach(string maDocGia)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LichSuMuonSach_Result>("sp_LichSuMuonSach", maDocGiaParameter);
        }
    
        public virtual int sp_MoKhoaTaiKhoan(string maDocGia, ObjectParameter ketQua)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MoKhoaTaiKhoan", maDocGiaParameter, ketQua);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_ThanhToanPhieuPhat(Nullable<int> maPhieuPhat, ObjectParameter ketQua)
        {
            var maPhieuPhatParameter = maPhieuPhat.HasValue ?
                new ObjectParameter("MaPhieuPhat", maPhieuPhat) :
                new ObjectParameter("MaPhieuPhat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanPhieuPhat", maPhieuPhatParameter, ketQua);
        }
    
        public virtual int sp_ThemViPham(Nullable<int> maPhieuMuon, string loaiViPham, ObjectParameter ketQua)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var loaiViPhamParameter = loaiViPham != null ?
                new ObjectParameter("LoaiViPham", loaiViPham) :
                new ObjectParameter("LoaiViPham", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemViPham", maPhieuMuonParameter, loaiViPhamParameter, ketQua);
        }
    
        public virtual ObjectResult<sp_TimSach_Result> sp_TimSach(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimSach_Result>("sp_TimSach", tuKhoaParameter);
        }
    
        public virtual int sp_TraSach(Nullable<int> maPhieuMuon, ObjectParameter ketQua)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TraSach", maPhieuMuonParameter, ketQua);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_XacNhanNhanSach(Nullable<int> maPhieuMuon, Nullable<int> maThuThu, ObjectParameter ketQua)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var maThuThuParameter = maThuThu.HasValue ?
                new ObjectParameter("MaThuThu", maThuThu) :
                new ObjectParameter("MaThuThu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XacNhanNhanSach", maPhieuMuonParameter, maThuThuParameter, ketQua);
        }
    
        public virtual ObjectResult<sp_XemPhieuPhat_Result> sp_XemPhieuPhat(string maDocGia)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemPhieuPhat_Result>("sp_XemPhieuPhat", maDocGiaParameter);
        }
    
        public virtual ObjectResult<sp_XemThongBao_Result> sp_XemThongBao(string maDocGia)
        {
            var maDocGiaParameter = maDocGia != null ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemThongBao_Result>("sp_XemThongBao", maDocGiaParameter);
        }
    
        public virtual int sp_XuLyKhongLaySach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XuLyKhongLaySach");
        }
    }
}
