//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DocGia
    {
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TenDangNhap { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayKhoa { get; set; }
        public Nullable<System.DateTime> NgayMoKhoa { get; set; }
    }
}
