//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PhieuPhat
    {
        public int MaPhieuPhat { get; set; }
        public int MaPhieuMuon { get; set; }
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string TenSach { get; set; }
        public System.DateTime NgayLapPhieu { get; set; }
        public System.DateTime HanThanhToan { get; set; }
        public decimal TongTienPhat { get; set; }
        public string TrangThai { get; set; }
    }
}
