//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SachQuaHan
    {
        public int MaPhieuMuon { get; set; }
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string TenSach { get; set; }
        public Nullable<System.DateTime> NgayNhanSach { get; set; }
        public Nullable<System.DateTime> HanTra { get; set; }
        public Nullable<int> SoNgayQuaHan { get; set; }
    }
}
