//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int MaViPham { get; set; }
        public int MaPhieuMuon { get; set; }
        public Nullable<int> MaPhieuPhat { get; set; }
        public string LoaiViPham { get; set; }
        public Nullable<int> SoNgayQuaHan { get; set; }
        public decimal TienPhat { get; set; }
        public string TrangThai { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual PhieuPhat PhieuPhat { get; set; }
    }
}
